const Ticket = require('../models/Ticket');
const Event = require('../models/Event');
const User = require('../models/User');

// @desc    Buy ticket (Etkinliğe Katılım Bildirimi)
// @route   POST /api/tickets
// @access  Private
const buyTicket = async (req, res) => {
    try {
        const { eventId } = req.body;

        if (!eventId) {
            return res.status(400).json({ message: 'Event ID required' });
        }

        // Check if event exists and is active

        const event = await Event.findById(eventId);
        if (!event) {
            return res.status(404).json({ message: 'Event not found' });
        }

        if (event.status !== 'active') {
            return res.status(400).json({ message: 'This event is no longer active' });
        }

        // Check capacity
        const soldTickets = await Ticket.countDocuments({
            event: eventId,
            status: { $ne: 'cancelled' }
        });

        if (soldTickets >= event.capacity) {
            return res.status(400).json({ message: 'Event is sold out' });
        }

        // Check if user already has an active ticket
        const existingTicket = await Ticket.findOne({
            event: eventId,
            user: req.user.id,
            status: 'active'
        });

        if (existingTicket) {
            return res.status(400).json({ 
                message: 'You already have an active ticket for this event' 
            });
        }

        // Create ticket (ticket code is auto-generated by pre-save hook)
        const ticket = await Ticket.create({
            event: eventId,
            user: req.user.id,
            price: event.price,
            status: 'active'
        });

        // Populate event and user details
        const populatedTicket = await Ticket.findById(ticket._id)
            .populate('event')
            .populate('user', 'firstName lastName email');

        res.status(201).json({
            message: 'Ticket purchased successfully',
            ticket: populatedTicket
        });
    } catch (error) {
        console.error('Buy ticket error:', error);
        res.status(500).json({ 
            message: 'Server error during ticket purchase',
            error: error.message 
        });
    }
};

// @desc    Get user's tickets (Kullanıcının Biletlerini Listeleme)
// @route   GET /api/tickets/my-tickets
// @access  Private
const getUserTickets = async (req, res) => {
    try {
        const tickets = await Ticket.find({ 
            user: req.user.id,
            status: { $ne: 'cancelled' }
        })
        .populate({
            path: 'event',
            populate: {
                path: 'organizer',
                select: 'firstName lastName email'
            }
        })
        .sort({ purchaseDate: -1 });

        // Add event status info
        const ticketsWithInfo = tickets.map(ticket => {
            const event = ticket.event;
            const now = new Date();
            const eventDate = new Date(event.date);
            
            let eventStatus = 'upcoming';
            if (eventDate < now) {
                eventStatus = 'past';
            } else if (ticket.status === 'used') {
                eventStatus = 'attended';
            }

            return {
                ...ticket.toObject(),
                eventStatus
            };
        });

        res.json(ticketsWithInfo);
    } catch (error) {
        console.error('Get user tickets error:', error);
        res.status(500).json({ 
            message: 'Server error',
            error: error.message 
        });
    }
};

// @desc    Verify ticket (Katılım Kodunu Doğrulama)
// @route   POST /api/tickets/verify
// @access  Private
const verifyTicket = async (req, res) => {
    try {
        const { eventId, ticketCode } = req.body;

        if (!eventId || !ticketCode) {
            return res.status(400).json({ 
                message: 'Event ID and ticket code required' 
            });
        }

        // Check if event exists and user is organizer
        const event = await Event.findById(eventId);
        if (!event) {
            return res.status(404).json({ message: 'Event not found' });
        }

        // Check if user is event organizer or admin
        if (event.organizer.toString() !== req.user.id && req.user.role !== 'admin') {
            return res.status(403).json({ 
                message: 'Not authorized to verify tickets for this event' 
            });
        }

        // Find ticket
        const ticket = await Ticket.findOne({ 
            ticketCode: ticketCode.toUpperCase(),
            event: eventId
        }).populate('user', 'firstName lastName email');

        if (!ticket) {
            return res.status(404).json({ 
                valid: false,
                message: 'Invalid ticket code for this event' 
            });
        }

        // Check ticket status
        if (ticket.status === 'used') {
            return res.json({ 
                valid: false,
                message: 'Ticket has already been used',
                ticket: {
                    ticketCode: ticket.ticketCode,
                    user: ticket.user,
                    checkInTime: ticket.checkInTime
                }
            });
        }

        if (ticket.status === 'cancelled') {
            return res.json({ 
                valid: false,
                message: 'Ticket has been cancelled',
                ticket: {
                    ticketCode: ticket.ticketCode,
                    user: ticket.user
                }
            });
        }

        // Check if event date has passed
        const eventDate = new Date(event.date);
        const now = new Date();
        
        // If event date is in the future, just verify without checking in
        if (eventDate > now) {
            return res.json({ 
                valid: true,
                message: 'Valid ticket (Event not started yet)',
                ticket: {
                    ticketCode: ticket.ticketCode,
                    user: ticket.user,
                    purchaseDate: ticket.purchaseDate
                }
            });
        }

        // Mark ticket as used
        ticket.status = 'used';
        ticket.checkInTime = now;
        ticket.checkedInBy = req.user.id;
        await ticket.save();

        res.json({ 
            valid: true,
            message: 'Ticket verified and checked in successfully',
            ticket: {
                ticketCode: ticket.ticketCode,
                user: ticket.user,
                checkInTime: ticket.checkInTime
            }
        });
    } catch (error) {
        console.error('Verify ticket error:', error);
        res.status(500).json({ 
            valid: false,
            message: 'Server error during verification',
            error: error.message 
        });
    }
};

// @desc    Cancel ticket (Bilet İptal Etme)
// @route   DELETE /api/tickets/:id
// @access  Private
const cancelTicket = async (req, res) => {
    try {
        const ticket = await Ticket.findById(req.params.id)
            .populate('event');

        if (!ticket) {
            return res.status(404).json({ message: 'Ticket not found' });
        }

        // Check if user owns the ticket or is admin
        if (ticket.user.toString() !== req.user.id && req.user.role !== 'admin') {
            return res.status(403).json({ 
                message: 'Not authorized to cancel this ticket' 
            });
        }

        // Check if ticket can be cancelled (not used, not already cancelled)
        if (ticket.status === 'used') {
            return res.status(400).json({ 
                message: 'Cannot cancel a ticket that has already been used' 
            });
        }

        if (ticket.status === 'cancelled') {
            return res.status(400).json({ 
                message: 'Ticket is already cancelled' 
            });
        }

        // Check if event date hasn't passed
        const eventDate = new Date(ticket.event.date);
        const now = new Date();
        
        if (eventDate < now) {
            return res.status(400).json({ 
                message: 'Cannot cancel ticket for past events' 
            });
        }

        // Cancel ticket
        ticket.status = 'cancelled';
        await ticket.save();

        res.json({ 
            message: 'Ticket cancelled successfully',
            ticket: {
                id: ticket._id,
                ticketCode: ticket.ticketCode,
                status: ticket.status,
                event: ticket.event.title
            }
        });
    } catch (error) {
        console.error('Cancel ticket error:', error);
        res.status(500).json({ 
            message: 'Server error during ticket cancellation',
            error: error.message 
        });
    }
};

// @desc    Get ticket by code
// @route   GET /api/tickets/code/:code
// @access  Private
const getTicketByCode = async (req, res) => {
    try {
        const { code } = req.params;

        const ticket = await Ticket.findOne({ ticketCode: code.toUpperCase() })
            .populate('event')
            .populate('user', 'firstName lastName email');

        if (!ticket) {
            return res.status(404).json({ message: 'Ticket not found' });
        }

        res.json(ticket);
    } catch (error) {
        console.error('Get ticket by code error:', error);
        res.status(500).json({ 
            message: 'Server error',
            error: error.message 
        });
    }
};

// @desc    Check ticket availability for event
// @route   GET /api/tickets/event/:eventId/availability
// @access  Public
const checkAvailability = async (req, res) => {
    try {
        const { eventId } = req.params;

        const event = await Event.findById(eventId);
        if (!event) {
            return res.status(404).json({ message: 'Event not found' });
        }

        const soldTickets = await Ticket.countDocuments({
            event: eventId,
            status: { $ne: 'cancelled' }
        });

        const available = event.capacity - soldTickets;

        res.json({
            eventId: event._id,
            eventTitle: event.title,
            totalCapacity: event.capacity,
            soldTickets,
            availableSpots: available,
            isSoldOut: available <= 0
        });
    } catch (error) {
        console.error('Check availability error:', error);
        res.status(500).json({ 
            message: 'Server error',
            error: error.message 
        });
    }
};

// @desc    Bulk verify tickets (for scanning multiple tickets)
// @route   POST /api/tickets/bulk-verify
// @access  Private
const bulkVerifyTickets = async (req, res) => {
    try {
        const { eventId, ticketCodes } = req.body;

        if (!eventId || !ticketCodes || !Array.isArray(ticketCodes)) {
            return res.status(400).json({ 
                message: 'Event ID and ticket codes array required' 
            });
        }

        // Check if event exists and user is organizer
        const event = await Event.findById(eventId);
        if (!event) {
            return res.status(404).json({ message: 'Event not found' });
        }

        if (event.organizer.toString() !== req.user.id && req.user.role !== 'admin') {
            return res.status(403).json({ 
                message: 'Not authorized to verify tickets for this event' 
            });
        }

        const results = [];
        const now = new Date();

        for (const code of ticketCodes) {
            const ticket = await Ticket.findOne({ 
                ticketCode: code.toUpperCase(),
                event: eventId
            }).populate('user', 'firstName lastName email');

            if (!ticket) {
                results.push({
                    ticketCode: code,
                    valid: false,
                    message: 'Invalid ticket code'
                });
                continue;
            }

            if (ticket.status === 'used') {
                results.push({
                    ticketCode: code,
                    valid: false,
                    message: 'Ticket already used',
                    ticket: {
                        user: ticket.user,
                        checkInTime: ticket.checkInTime
                    }
                });
                continue;
            }

            if (ticket.status === 'cancelled') {
                results.push({
                    ticketCode: code,
                    valid: false,
                    message: 'Ticket cancelled',
                    ticket: { user: ticket.user }
                });
                continue;
            }

            // Mark as used
            ticket.status = 'used';
            ticket.checkInTime = now;
            ticket.checkedInBy = req.user.id;
            await ticket.save();

            results.push({
                ticketCode: code,
                valid: true,
                message: 'Successfully checked in',
                ticket: {
                    user: ticket.user,
                    checkInTime: now
                }
            });
        }

        res.json({
            totalProcessed: results.length,
            successful: results.filter(r => r.valid).length,
            failed: results.filter(r => !r.valid).length,
            results
        });
    } catch (error) {
        console.error('Bulk verify error:', error);
        res.status(500).json({ 
            message: 'Server error during bulk verification',
            error: error.message 
        });
    }
};

module.exports = {
    buyTicket,
    getUserTickets,
    verifyTicket,
    getEventParticipants,
    cancelTicket,
    getTicketByCode,
    checkAvailability,
    bulkVerifyTickets
};