const Ticket = require('../models/Ticket');
const Event = require('../models/Event');
const User = require('../models/User');

// @desc    Buy ticket (Etkinliğe Katılım Bildirimi)
// @route   POST /api/tickets
// @access  Private
exports.buyTicket = async (req, res) => {
    try {
        const { eventId } = req.body;

        if (!eventId) {
            return res.status(400).json({ message: 'Event ID required' });
        }

        // Check if event exists and is active
        const event = await Event.findById(eventId);
        if (!event) {
            return res.status(404).json({ message: 'Event not found' });
        }

        if (event.status !== 'active') {
            return res.status(400).json({ message: 'This event is no longer active' });
        }

        // Check capacity
        const soldTickets = await Ticket.countDocuments({
            event: eventId,
            status: { $ne: 'cancelled' }
        });

        if (soldTickets >= event.capacity) {
            return res.status(400).json({ message: 'Event is sold out' });
        }

        // Check if user already has an active ticket
        const existingTicket = await Ticket.findOne({
            event: eventId,
            user: req.user.id,
            status: 'active'
        });

        if (existingTicket) {
            return res.status(400).json({ 
                message: 'You already have an active ticket for this event' 
            });
        }

        // Create ticket (ticket code is auto-generated by pre-save hook)
        const ticket = await Ticket.create({
            event: eventId,
            user: req.user.id,
            price: event.price,
            status: 'active'
        });

        // Populate event and user details(event details automatically)
        const populatedTicket = await Ticket.findById(ticket._id)
            .populate('event')
            .populate('user', 'firstName lastName email');

        res.status(201).json({
            message: 'Ticket purchased successfully',
            ticket: populatedTicket
        });
    } catch (error) {
        console.error('Buy ticket error:', error);
        res.status(500).json({ 
            message: 'Server error during ticket purchase',
            error: error.message 
        });
    }
};
