services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    restart: always
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" #Port RabbitMQ send/receive messages
      - "15672:15672" #Port RabbitMQ management interface

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  mobilfrontend:
    build:
      context: ./MobilFrontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - EXPO_PUBLIC_API_URL=https://guydebadinga-events.serveousercontent.com/api
      - EXPO_PACKAGER_PROXY_URL=https://natural-stylized-marbles.ngrok-free.dev
    command: npx expo start --lan --clear
    depends_on:
      - backend
      - backend-tunnel
    restart: always
    tty: true
    stdin_open: true

  backend-tunnel:
    image: alpine:latest
    restart: always
    volumes:
      - ssh-data:/root/.ssh
    command:
      - sh
      - -c
      - |
        apk add --no-cache openssh-client
        mkdir -p /root/.ssh
        chmod 700 /root/.ssh
        if [ ! -f /root/.ssh/id_rsa ]; then
          ssh-keygen -t rsa -b 2048 -N "" -f /root/.ssh/id_rsa
        fi
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -R guydebadinga-events:80:backend:5000 serveo.net

  expo-tunnel:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=3EX2Df6HVUHmhzA7vt4OoEPqZ6F_2CQCUH2ibByyKMKWGydwj
    command:
      - http
      - mobilfrontend:8081
      - --url=natural-stylized-marbles.ngrok-free.dev
      - --log=stdout

volumes:
  ssh-data:

