/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/hello-wave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/parallax-scroll-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/hello-wave`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/parallax-scroll-view`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/../components/external-link${`?${string}` | `#${string}` | ''}` | `/../components/haptic-tab${`?${string}` | `#${string}` | ''}` | `/../components/hello-wave${`?${string}` | `#${string}` | ''}` | `/../components/parallax-scroll-view${`?${string}` | `#${string}` | ''}` | `/../components/themed-text${`?${string}` | `#${string}` | ''}` | `/../components/themed-view${`?${string}` | `#${string}` | ''}` | `/../constants/theme${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme.web${`?${string}` | `#${string}` | ''}` | `/../hooks/use-theme-color${`?${string}` | `#${string}` | ''}` | `/../components/ui/collapsible${`?${string}` | `#${string}` | ''}` | `/../components/ui/icon-symbol.ios${`?${string}` | `#${string}` | ''}` | `/../components/ui/icon-symbol${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/hello-wave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/parallax-scroll-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/icon-symbol`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
